export enum NotificationAction {
  NEW = 'Created',
  BULK_EDIT = 'BulkUpdate',
  EDIT = 'Updated',
  DELETE = 'Deleted',
}

export enum NotificationEntity {
  ORGANISATION = 'Organisation',
  ANNOUNCEMENT = 'Announcement',
  USER_REQUEST = 'Request',
  VOTE = 'Vote',
  MEETING = 'Meeting',
  BOOKING = 'Booking',
  WORKFLOW = 'Workflow',
  TASK = 'Task',
  WORKORDER = 'Workorder',
  INVOICE = 'Invoice',
  QUOTE = 'Quote',
  EVIDENCE = 'Evidence',
  EMAIL = 'Email',
  COMMENT = 'Comment',
  ATTACHMENT = 'Attachment',
  IMAGE = 'Image',
  USER = 'User',
  GROUP = 'Group',
  ASSET = 'Asset',
  DOCUMENT = 'Document',
  VENDOR = 'Vendor',
  SUBMIT = 'Submit',
  CATEGORY = 'Category',
  BOOKING_TYPE = 'BookingType',
  ASSET_TYPE = 'AssetType',
  EVENT = 'Event',
  INFORMATION = 'Information',
  TRANSACTION = 'Transaction',
  FINANCIAL_YEAR = 'FinancialYear',
  CHART_OF_ACCOUNT = 'ChartOfAccount',
  BUDGET = 'Budget',
  FOLDER = 'Folder',
}
