export enum AIQuestionType {
  SUMMARIZE = 'SUMMARIZE',
  EXPLAIN = 'EXPLAIN',
  VERIFY = 'VERIFY',
  RECOMMENDATION = 'RECOMMENDATION',
  SEARCH = 'SEARCH',
  DRAFT = 'DRAFT',
  ANOMALY_DETECTION = 'ANOMALY_DETECTION',
  CONVERSATION = 'CONVERSATION',
}
