export enum BusinessModule {
  GENERAL = 'GENERAL',
  USER = 'USER',
  WORKFLOW = 'WORKFLOW',
  VENDOR = 'VENDOR',
  COMMUNICATION = 'COMMUNICATION',
  ASSET = 'ASSET',
  ANALYTICS = 'ANALYTICS',
  AI = 'AI',
  FINANCE = 'FINANCE',
}
